#!/bin/sh

if [ "$1" = "" ]; then
	URL='http://www.openbsd.org/cgi-bin/man.cgi?query='
else
	URL=$1
fi

# assume mdown and thus don't replace in <pre><code> lines
sed '/^  /!s,\([a-z0-9\.]*\)(\([0-9]\)),[\1(\2)]('$URL'\1),g'
